---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: plex-config
    volumeAttributes:
      source: "//192.168.1.100/plex-config"
    nodeStageSecretRef:
      name: cifs-secret
      namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tv-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: plex-tv
    volumeAttributes:
      source: "//192.168.1.100/plex-tv"
    nodeStageSecretRef:
      name: cifs-secret
      namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-movies-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: plex-movies
    volumeAttributes:
      source: "//192.168.1.100/plex-movies"
    nodeStageSecretRef:
      name: cifs-secret
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: plex-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-tv-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: plex-tv-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: plex-movies-pv
