apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          ports:
            - containerPort: 32400
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: VERSION
              value: docker
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /data/tv
            - name: movies
              mountPath: /data/movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config-pvc
        - name: tv
          persistentVolumeClaim:
            claimName: plex-tv-pvc
        - name: movies
          persistentVolumeClaim:
            claimName: plex-movies-pvc
